/**
 * Articoli della sezione canton-vd (Vaud). Stessa forma `Article` del
 * registro frontaliere; scritto da generator/scripts/create-article.mjs
 * --section=canton-vd.
 */
import type { Article } from '../../blog-articles-data';

export const CANTON_ARTICLES: Article[] = [
 {
 id: 'cdhr-frontalieri-vaud-2026',
 category: 'fiscale',
 date: '2026-10-07T10:21:57.438Z',
 image: '/images/blog/article-cdhr-frontalieri-vaud-2026.webp',
 hasCalculator: true,
 articleType: 'news',
 canton: ['VD'],
 authorSlug: 'marco-ferrari',
 authorName: 'Marco Ferrari',
 },
 {
 id: 'vaud-revision-bouclier-fiscal-2024',
 category: 'fiscale',
 date: '2026-10-07T10:47:31.180Z',
 image: '/images/blog/article-vaud-revision-bouclier-fiscal-2024.webp',
 hasCalculator: true,
 articleType: 'news',
 canton: ['VD'],
 authorSlug: 'marco-ferrari',
 authorName: 'Marco Ferrari',
 },
 {
 id: 'losanna-budget-deficit-2027',
 category: 'novita',
 date: '2026-10-07T11:12:50.818Z',
 image: '/images/blog/article-losanna-budget-deficit-2027.webp',
 hasCalculator: true,
 articleType: 'news',
 canton: ['VD'],
 authorSlug: 'redazione',
 authorName: 'Redazione Frontaliere Ticino',
 },
 {
 id: 'morges-mobilita-consultazione-2045',
 category: 'novita',
 date: '2026-10-08T11:29:50.102Z',
 image: '/images/blog/article-morges-mobilita-consultazione-2045.webp',
 hasCalculator: true,
 articleType: 'news',
 canton: ['VD'],
 authorSlug: 'redazione',
 authorName: 'Redazione Frontaliere Ticino',
 },
 {
 id: 'vaud-budget-2027-revisione-12percento',
 category: 'fiscale',
 date: '2026-10-08T11:43:59.351Z',
 image: '/images/blog/article-vaud-budget-2027-revisione-12percento.webp',
 hasCalculator: true,
 articleType: 'news',
 canton: ['VD'],
 authorSlug: 'marco-ferrari',
 authorName: 'Marco Ferrari',
 },
 {
 id: 'sussidi-malattia-lavoro-vaud',
 category: 'pratico',
 date: '2026-10-09T12:01:29.729Z',
 image: '/images/blog/article-sussidi-malattia-lavoro-vaud.webp',
 hasCalculator: true,
 articleType: 'news',
 canton: ['VD'],
 authorSlug: 'laura-bianchi',
 authorName: 'Laura Bianchi',
 },
 {
 id: 'perdite-agricole-canton-vaud-caldo',
 category: 'novita',
 date: '2026-10-09T12:27:10.778Z',
 image: '/images/blog/article-perdite-agricole-canton-vaud-caldo.webp',
 hasCalculator: true,
 articleType: 'news',
 canton: ['VD'],
 authorSlug: 'redazione',
 authorName: 'Redazione Frontaliere Ticino',
 },
];
