/**
 * Articoli della sezione canton-be (Berna). Stessa forma `Article` del
 * registro frontaliere; scritto da generator/scripts/create-article.mjs
 * --section=canton-be.
 */
import type { Article } from '../../blog-articles-data';

export const CANTON_ARTICLES: Article[] = [
 {
 id: 'simplificazione-imposta-trasferimento-berna',
 category: 'fiscale',
 date: '2026-10-07T06:54:25.689Z',
 image: '/images/blog/article-simplificazione-imposta-trasferimento-berna.webp',
 hasCalculator: true,
 articleType: 'news',
 canton: ['BE'],
 authorSlug: 'marco-ferrari',
 authorName: 'Marco Ferrari',
 },
 {
 id: 'wabern-tram-risanamento',
 category: 'pratico',
 date: '2026-10-07T07:11:43.423Z',
 image: '/images/blog/article-wabern-tram-risanamento.webp',
 hasCalculator: true,
 articleType: 'news',
 canton: ['BE'],
 authorSlug: 'redazione',
 authorName: 'Redazione Frontaliere Ticino',
 },
 {
 id: 'disoccupazione-berna-settembre-2026-stabile',
 category: 'pratico',
 date: '2026-10-07T19:58:52.255Z',
 image: '/images/blog/article-disoccupazione-berna-settembre-2026-stabile.webp',
 hasCalculator: true,
 articleType: 'news',
 canton: ['BE'],
 authorSlug: 'redazione',
 authorName: 'Redazione Frontaliere Ticino',
 },
 {
 id: 'ipsach-gru-linea-strada',
 category: 'pratico',
 date: '2026-10-08T19:26:56.613Z',
 image: '/images/blog/article-ipsach-gru-linea-strada.webp',
 hasCalculator: true,
 articleType: 'news',
 canton: ['BE'],
 authorSlug: 'redazione',
 authorName: 'Redazione Frontaliere Ticino',
 },
 {
 id: 'berna-familiari-curanti-incontro',
 category: 'novita',
 date: '2026-10-09T06:53:22.557Z',
 image: '/images/blog/article-berna-familiari-curanti-incontro.webp',
 hasCalculator: true,
 articleType: 'news',
 canton: ['BE'],
 authorSlug: 'redazione',
 authorName: 'Redazione Frontaliere Ticino',
 },
 {
 id: 'cyberattacco-casse-pensione-berna',
 category: 'pensione',
 date: '2026-10-09T23:26:36.398Z',
 image: '/images/blog/article-cyberattacco-casse-pensione-berna.webp',
 hasCalculator: true,
 articleType: 'news',
 canton: ['BE'],
 authorSlug: 'laura-bianchi',
 authorName: 'Laura Bianchi',
 },
 {
 id: 'traffico-berna-manifestazione',
 category: 'pratico',
 date: '2026-10-10T07:15:47.682Z',
 image: '/images/blog/article-traffico-berna-manifestazione.webp',
 hasCalculator: true,
 articleType: 'news',
 canton: ['BE'],
 authorSlug: 'redazione',
 authorName: 'Redazione Frontaliere Ticino',
 },
];
